name: MedeX Simple Deploy

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push
        run: |
          docker build -t medex .
          docker tag medex:latest 319125697079.dkr.ecr.ap-south-1.amazonaws.com/medexchatbot:latest
          docker push 319125697079.dkr.ecr.ap-south-1.amazonaws.com/medexchatbot:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            # install aws if needed
            if ! command -v aws &> /dev/null
            then
              sudo apt update
              sudo apt install unzip curl -y
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip -o awscliv2.zip
              sudo ./aws/install
            fi

            # login
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 319125697079.dkr.ecr.ap-south-1.amazonaws.com

            # pull
            docker pull 319125697079.dkr.ecr.ap-south-1.amazonaws.com/medexchatbot:latest

            # restart
            docker stop medex-container || true
            docker rm medex-container || true

            docker run -d -p 8080:8080 \
              --name medex-container \
              -e PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }} \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              319125697079.dkr.ecr.ap-south-1.amazonaws.com/medexchatbot:latest